# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('live', models.BooleanField(default=None)),
                ('event_code', models.CharField(max_length=100)),
                ('psp_reference', models.CharField(max_length=100)),
                ('original_reference', models.CharField(max_length=100)),
                ('merchant_reference', models.CharField(max_length=80)),
                ('merchant_account_code', models.CharField(max_length=128)),
                ('event_date', models.DateTimeField()),
                ('success', models.BooleanField(default=None)),
                ('payment_method', models.CharField(blank=True, max_length=40, null=True)),
                ('operations', models.TextField()),
                ('reason', models.TextField()),
                ('value', models.IntegerField(null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('additional_params', models.TextField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_adyen.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('live', models.BooleanField(default=None)),
                ('merchant_reference', models.CharField(max_length=80)),
                ('payment_amount', models.IntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('ship_before_date', models.DateField()),
                ('skin_code', models.CharField(max_length=8)),
                ('merchant_account', models.CharField(max_length=128)),
                ('shopper_locale', models.CharField(blank=True, max_length=35, null=True)),
                ('order_data', models.TextField(blank=True, null=True)),
                ('session_validity', models.DateTimeField()),
                ('merchant_return_data', models.CharField(max_length=128)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('shopper_email', models.CharField(blank=True, max_length=254, null=True)),
                ('shopper_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('allowed_methods', models.TextField(blank=True)),
                ('blocked_methods', models.TextField(blank=True)),
                ('offset', models.IntegerField(null=True)),
                ('brand_code', models.CharField(blank=True, max_length=40, null=True)),
                ('issuer_id', models.CharField(blank=True, max_length=40, null=True)),
                ('shopper_statement', models.CharField(blank=True, max_length=135)),
                ('offer_email', models.TextField(blank=True, null=True)),
                ('res_url', models.CharField(blank=True, max_length=2083, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('live', models.NullBooleanField()),
                ('auth_result', models.CharField(max_length=10)),
                ('psp_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_reference', models.CharField(max_length=80)),
                ('skin_code', models.CharField(max_length=8)),
                ('payment_method', models.CharField(blank=True, max_length=40, null=True)),
                ('shopper_locale', models.CharField(max_length=35)),
                ('merchant_return_data', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
